name: display secret key
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      AWS_KEY: ${{secrets.AWS_ACCESS_KEY_ID}}
    steps:
      - name: checkout code
        uses: action/checkout@v3

      - name: run command
        run: echo "displaying secrets"

      - name: print aws key ID
        run: echo "using secret $AWS_KEY"